# This is a basic workflow to help you get started with Actions

name: T-Login Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Test Os
        run: uname -r 
      - name: Pc -Name
        run: whoami
      - name: working locate
        run: pwd
      - name: files
        run: ls -a
      - name: bash version
        run: bash --version

      # Runs a set of commands using the runners shell
      - name: Test Banner 
        run: |
          sed -i -e "s/bash .sbanner.sh/echo 'banner'/g" T-Login.sh
          dirrs="/data/data/com.termux/files/usr/etc/bash.bashrc"
          bann="bash /data/data/com.termux/files/usr/etc/.mbanner.sh"
          sed -i -e "s/$dirrs/~/g" T-Login.sh
          sed -i -e "s/${bann}/echo 'banner'/g" create.sh
          sed -i -e "s/${bann}/echo 'banner'/g" Termux-Login.sh
          bash T-Login.sh<<!
          test
          Ubuntu
          Prajwal-usr
          psk
          psk
          !
          cat ~/.Login
